<?php
/**
 * Created by PhpStorm.
 * User:  pso318
 * Date: 2018/7/31
 * Time: 15:31
 */

namespace app\index\controller;


use think\Controller;

class Common extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cate = $this->getcate();
        // 获取当前访问一级栏目唯一标识
        $currcontroller = request()->controller();
        $currtype = $this->getcurrtype($currcontroller);
        // 获取网站配置信息
        $config = db('config')->field('config')->find();
        $config = json_decode($config['config'],true);
        if(!isset($config['state'])){
            $config['state'] = 0;
        }
        // 判断网站的状态
        $this->checkwebstatus($config['state'],$config['closeinfo']);
        $this->assign([
            'cate' => $cate,
            'currtype' => $currtype,
            'config' => $config,
        ]);
    }

    /**
     * 获取导航栏目信息
     * @return mixed
     */
    private function getcate(){
        $res = db('category')->where('pid',0)->where('isshow',1)->order('sort desc,id Asc')->field('id,name,type')->select();
        foreach ($res as $k => $v){
            $res_child = db('category')->where('pid',$v['id'])->where('isshow',1)->order('sort desc,id Asc')->field('id,name,type')->select();
            $res[$k]['child'] = $res_child;
        }
        return $res;
    }

    private function getcurrtype($controller){
        switch ($controller){
            case 'Index':
                return 0;
            case 'Page':
                return 1;
            case 'Pictures':
                return 2;
            case 'News':
                return 3;
            case 'Contact':
                return 4;
            default:
                return 0;
        }
    }

    private function checkwebstatus($status,$info="网站关闭"){
        if ($status != 1){
            header('Content-Type:text/html;charset=utf-8'); // 设置header编码，防止输出信息乱码
            echo $info;
            exit;
        }
    }

    // 左侧的子栏目列表
    protected function getchild($mark='about'){
        $res = db('category')->where('mark',$mark)->field('id,name,type')->select();
        return $res;
    }

    // 获取当前位置  格式为：首页>顶级栏目>子栏目>当前栏目

    /**
     * @param $id  当前栏目的id
     */
  /*  protected function getlocation($id){
        $cate = db('category')->where('id',$id)->field('id,name,pid')->find();
        $arr = [];
        if ($cate){
            $arr[] = $cate['name'];
            if ($cate['pid'] != 0){
                $pre_cate = $this->getlocation($cate['pid']);
                $arr = array_merge($pre_cate,$arr);
            }
            return $arr;
        }
    }*/

}